import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ViewTransitions } from "next-view-transitions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ViewTransitions>
            <html lang="en">
                <body className={inter.className}>
                    <nav className="flex h-12 bg-black text-white shadow-md sticky">
                        <ul className="flex">
                            <li className="p-3">
                                <Link href="/framer-motion">Framer Motion</Link>
                            </li>
                            <li className="p-3">
                                <Link href="/view-transitions">
                                    Next View Transition
                                </Link>
                            </li>
                        </ul>
                    </nav>
                    {children}
                </body>
            </html>
        </ViewTransitions>
    );
}
